### ISSUE TITLE
Profile URL - headers already sent error

### ISSUE THREAD

**Issue by benyates1** [ghoshnirmalya/User-Profile#1]
When attempting to access a profile from a direct URL - example: http://xxxxxx.com/UserName - a 'headers already sent' error appears as below;

`Warning: Cannot modify header information - headers already sent by (output started at /public_html/_dev/users/v4/user-profile.php:2) in /public_html/_dev/users/v4/components/session-check-user-profile.php on line 7`

**Comment by ghoshnirmalya** [comment]
You can comment out these three lines and see if your issues are resolved.

Also, you can try this: http://www.infismash.com/creating-a-user-profile-using-php-and-mysqli/#comment-29023

**Comment by benyates1** [comment]
What three lines?

**Comment by ghoshnirmalya** [comment]
Edited the previous comment.

**Comment by ghoshnirmalya** [comment]
Closing this since I'm assuming that the fix solved your problem. If the issue persists, feel free to open a new issue.
