### ISSUE TITLE
A few questions?

### ISSUE THREAD

**Issue by eddiejibson** [ghoshnirmalya/User-Profile#5]
-

**Comment by ghoshnirmalya** [comment]
This project hasn't been maintained. I was planning to update it in the future. Will try to integrate your idea into it as well.

**Comment by eddiethejibson** [comment]
@ghoshnirmalya Great, thanks. If you want me to help with front-end, I'm pretty good - especially with Material designs. Let me know if you do, I have some good ideas. I like a challenge, and think this will be a good one.

**Comment by ghoshnirmalya** [comment]
You can fork the repo and customize it. Feel free to create pull requests.

**Comment by eddiethejibson** [comment]
@ghoshnirmalya Ok, I'll start now. Hopefully you like material design haha

**Comment by ghoshnirmalya** [comment]
@m1screant Are you working on creating a pull request or should I close this issue?

**Comment by NewCastle252** [comment]
Could you help  me with this problem?
message shows that ( Field ‘user_backgroundpicture’ doesn’t have a default value)

**Comment by ghoshnirmalya** [comment]
@NewCastle252 https://stackoverflow.com/a/15438939/1928724.

**Comment by Florin-Corcaci** [comment]
Undefined index: user_name  in  session-check-index.php on line 4
Notice: Undefined index: user_username in  check-username-availability.php on line 4
--

**Comment by NewCastle252** [comment]
Super thnx

**Comment by hakanelver** [comment]
its not work on laragon 5 and php 5.6 newer versions.. too many errors at php codes. such as undefined index and session starts. you waste my time(about 45 minutes)  for notting. half share half works full in this site by you.  god dammed why github full of fakes and adverts..

**Comment by ghoshnirmalya** [comment]
@hakanelver This project was created 3 years ago and it hasn't been maintained. I added a note of that in the readme (https://github.com/ghoshnirmalya/User-Profile#nb). 

If anyone is interested in maintaining this project, I'll be glad to transfer this repository.
